 <!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <link href="stylehtml.css" rel="stylesheet" type="text/css"/>
        <title>HOME PAGE</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body class ="body">
        <div class="mHeader">
            &nbsp;&nbsp;<span class="style10"><strong>CAR COMPARING SYSTEM </strong></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <img  Height="90px" src="/Images/cclogo.gif" Width="200px" />

        </div>
                    <div class="menu"> 
                        
                        
                        
                        <ul>
                            <li><a href="index.php">HOME</a></li>
                            
                            <li><a href="?controller=login&action=login">LOGIN</a></li>
                            <li><a href="?controller=homePage&action=about">ABOUT US</a></li>
                            <li><a href="?controller=customer&action=view">VIEW CARS</a></li>
                           <!--<a href='?controller=lecturer&action=showClassList'>Show class list</a><br>-->
                          </ul>
                      

                    </div>
        <div class="mContent" align ="center"> <font size ="6"> CONTACT PAGE</font>
        
        <form action="" method ="">
                <h2>
        Welcome to vehicle comparing system
    </h2>
    <p>
        The home of good, quality and affordable vehicles.</p>
    <p>
   
        &nbsp;
        
        &nbsp;
        
    </p>


    <table>
        <tr>
            <td>
                <font size="4" style="color: red">CONTACT US:</font> <br>
                <font size="2" >Email : carcomparison@yahoo.com</font> <br>
                <font size="2" >Tel : 013 4125 458</font> <br>
                
                
                  
                  <font size="4" style="color: red">FIND US ON:</font> <br>
                <font size="2" >Facebook: Car Comparison Services!!</font> <br>
        </td>
           <td>
        <img  src="/UploadedPictures/unnamed (1).jpg" Width="317px" /> 
           </td>
           <td>
                 
                            
                </div>
           </td>
           
        </tr>
    </table>
        </form>
            
        </div>     
    </body>
    
</html>


